import {
  IconAlertCircle,
  IconApps,
  IconArrowDown,
  IconArrowUp,
  IconBook,
  IconBriefcase,
  IconCalendar,
  IconCamera,
  IconCar,
  IconCaravan,
  IconChartLine,
  IconChecklist,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCopy,
  IconDatabase,
  IconDeviceDesktop,
  IconDirectionSign,
  IconDownload,
  IconGripVertical,
  IconHome,
  IconLoader,
  IconMap,
  IconMapPin,
  IconMinus,
  IconMusic,
  IconMoon,
  IconPaperclip,
  IconPencil,
  IconPhoto,
  IconPlane,
  IconPlus,
  IconRefresh,
  IconRoute,
  IconSearch,
  IconShip,
  IconShirtSport,
  IconShoppingCart,
  IconStretching,
  IconSun,
  IconSunHigh,
  IconTarget,
  IconTicket,
  IconTrash,
  IconTruck,
  IconToolsKitchen2,
  IconWallet,
  IconX,
} from '@tabler/icons-react';
import type { SVGProps } from 'react';

export const PLATFORM_ICON_NAMES = [
  'apps',
  'book',
  'briefcase',
  'calendar',
  'chart-line',
  'checklist',
  'database',
  'home',
  'map',
  'music',
  'photo',
  'plane',
  'route',
  'shirt-sport',
  'shopping-cart',
  'stretching',
  'target',
  'ticket',
  'tools-kitchen-2',
  'wallet',
  'weather-sun',
  'arrow-down',
  'arrow-up',
  'camera',
  'car',
  'caravan',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'circle-alert',
  'copy',
  'device-desktop',
  'download',
  'grip-vertical',
  'image',
  'loader',
  'map-pin',
  'minus',
  'moon',
  'paperclip',
  'pencil',
  'plus',
  'refresh',
  'search',
  'ship',
  'signpost',
  'sun',
  'trash',
  'truck',
  'x',
] as const;

export const PLATFORM_MANIFEST_ICON_NAMES = [
  'apps',
  'book',
  'briefcase',
  'calendar',
  'chart-line',
  'checklist',
  'database',
  'home',
  'map',
  'music',
  'photo',
  'plane',
  'route',
  'shirt-sport',
  'shopping-cart',
  'stretching',
  'target',
  'ticket',
  'tools-kitchen-2',
  'wallet',
  'weather-sun',
] as const satisfies readonly (typeof PLATFORM_ICON_NAMES)[number][];

export type PlatformIconName = (typeof PLATFORM_ICON_NAMES)[number];

const icons = {
  apps: IconApps,
  book: IconBook,
  briefcase: IconBriefcase,
  calendar: IconCalendar,
  'chart-line': IconChartLine,
  checklist: IconChecklist,
  database: IconDatabase,
  home: IconHome,
  map: IconMap,
  music: IconMusic,
  photo: IconPhoto,
  plane: IconPlane,
  route: IconRoute,
  'shirt-sport': IconShirtSport,
  'shopping-cart': IconShoppingCart,
  stretching: IconStretching,
  target: IconTarget,
  ticket: IconTicket,
  'tools-kitchen-2': IconToolsKitchen2,
  wallet: IconWallet,
  'weather-sun': IconSunHigh,
  'arrow-down': IconArrowDown,
  'arrow-up': IconArrowUp,
  camera: IconCamera,
  car: IconCar,
  caravan: IconCaravan,
  check: IconCheck,
  'chevron-down': IconChevronDown,
  'chevron-left': IconChevronLeft,
  'chevron-right': IconChevronRight,
  'chevron-up': IconChevronUp,
  'circle-alert': IconAlertCircle,
  copy: IconCopy,
  'device-desktop': IconDeviceDesktop,
  download: IconDownload,
  'grip-vertical': IconGripVertical,
  image: IconPhoto,
  loader: IconLoader,
  'map-pin': IconMapPin,
  minus: IconMinus,
  moon: IconMoon,
  paperclip: IconPaperclip,
  pencil: IconPencil,
  plus: IconPlus,
  refresh: IconRefresh,
  search: IconSearch,
  ship: IconShip,
  signpost: IconDirectionSign,
  sun: IconSun,
  trash: IconTrash,
  truck: IconTruck,
  x: IconX,
} satisfies Record<PlatformIconName, typeof IconApps>;

export type IconProps = Omit<SVGProps<SVGSVGElement>, 'name' | 'title'> & {
  name: PlatformIconName;
  label?: string;
  size?: string | number;
  stroke?: string | number;
};

export function Icon({ name, label, ...props }: IconProps) {
  const Component = icons[name];
  return label ? (
    <Component {...props} aria-label={label} role="img" />
  ) : (
    <Component {...props} aria-hidden="true" focusable="false" />
  );
}
